# Версия формата Docker Compose
#version: '3.8'

# Список всех контейнеров (сервисов) приложения
services:

  # --- БАЗА ДАННЫХ (PostgreSQL) ---
  database:
    # Сборка кастомного образа из Dockerfile в папке ./database
    build: ./database
    # Постоянное имя контейнера в системе
    container_name: devops-postgres
    # Переменные окружения (значения подставляются из файла .env)
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    healthcheck:
      # Какую команду выполнить внутри контейнера для проверки:
      # Утилита pg_isready проверяет, принимает ли Postgres подключения.
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s      # Как часто проверять (каждые 10 секунд)
      timeout: 5s        # Сколько времени ждать ответа (максимум 5 секунд)
      retries: 3         # Сколько раз разрешено ошибиться перед тем, как признать контейнер больным
      start_period: 10s  # Даем базе 10 секунд на первый запуск, в это время проверки не считаются ошибкой
    # --- КОНЕЦ БЛОКА HEALTHCHECK ---

    # Подключение постоянных хранилищ (томов)
    volumes:     
      # Именованный том для сохранения данных базы при перезапуске контейнера
      - pgdata:/var/lib/postgresql/data
    # Открытие порта внутри виртуальной сети Docker (изолировано от внешнего мира)
    ports:
      - ${DB_PORT}

  # --- БЭКЕНД (Node.js) ---
  backend:
    # Сборка образа приложения из Dockerfile в папке ./backend
    build: ./backend
    # Постоянное имя контейнера бэкенда
    container_name: devops-backend
    # Проброс динамического порта из .env наружу (ПК:Контейнер)
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    # Передача настроек подключения к БД и порта внутрь Node.js приложения
    environment:
      DB_HOST: database # Имя сервиса базы данных в качестве хоста
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      
      PORT: ${BACKEND_PORT}
    # Порядок запуска: бэкенд начнет стартовать только ПОСЛЕ контейнера database
    depends_on:
      database:
        condition: service_healthy
      

  # --- ФРОНТЕНД (Nginx / Интерфейс) ---
  frontend:
    # Сборка образа интерфейса из Dockerfile в папке ./frontend
    build: ./frontend
    # Постоянное имя контейнера фронтенда
    container_name: devops-frontend
    # Проброс стандартного веб-порта (доступен в браузере по http://localhost:8080)
    ports:
      - "8080:${FRONT_PORT}"
    # Порядок запуска: фронтенд стартует только ПОСЛЕ контейнера backend
    depends_on:
      - backend

# Объявление именованных томов, используемых в конфигурации
volumes:
  # Выделение изолированного места на диске под данные PostgreSQL
  pgdata:
