version: '3.8'

services:
  # 1. Контейнер базы данных
  database:
    image: postgres:16-alpine
    container_name: devops-postgres
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: employees_db
    volumes:
      # Прокидываем скрипт инициализации в дефолтную папку Postgres
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Сохраняем данные БД на хосте, чтобы они не стирались при перезапуске
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  # 2. Контейнер бэкенда (Node.js)
  backend:
    build: ./backend
    container_name: devops-backend
    ports:
      - "5001:5001"
    environment:
      DB_HOST: database # Имя сервиса БД в сети Docker
      DB_USER: devops_user
      DB_PASSWORD: super_secret_password
      DB_NAME: employees_db
      PORT: 5001
    depends_on:
      - database

  # 3. Контейнер фронтенда (Nginx)
  frontend:
    build: ./frontend
    container_name: devops-frontend
    ports:
      - "8080:80" # Открываем фронтенд на порту 8080 вашего Mac
    depends_on:
      - backend

volumes:
  pgdata:
